const WORD_LIBRARY = {
  "OCEAN": {
    4: ["FISH", "CLAM", "CRAB", "TUNA", "WAVE", "SAND", "SALT", "TIDE", "REEF", "KELP", "SURF", "BOAT", "SHIP", "SAIL", "BASS", "ORCA", "BLUE"],
    5: ["SHARK", "WHALE", "CORAL", "SHELL", "BEACH", "SHORE", "WATER", "SQUID", "ALGAE", "DIVER", "SHOAL", "SKATE", "CONCH", "SCUBA", "POLYP"],
    6: ["TURTLE", "OYSTER", "ISLAND", "SPONGE", "MARLIN", "SAILOR", "LAGOON", "PIRATE", "SHRIMP", "MARINE", "TRENCH", "SEABED", "MUSSEL", "URCHIN"]
  },
  "SPACE": {
    4: ["MOON", "STAR", "MARS", "VOID", "DUST", "NASA", "NOVA", "ATOM", "TAIL", "RING", "HALO", "DARK", "WARP", "WAVE", "GLOW", "TIME", "SHIP", "LIFE"],
    5: ["ORBIT", "SOLAR", "COMET", "VENUS", "EARTH", "ALIEN", "LUNAR", "PLUTO", "TITAN", "LIGHT", "QUARK", "BOSON", "ALIEN", "FIELD", "FLARE", "GAMMA"],
    6: ["PLANET", "GALAXY", "METEOR", "ROCKET", "NEBULA", "SATURN", "URANUS", "APOLLO", "COSMOS", "QUASAR", "PULSAR", "PHOTON", "HUBBLE", "KEPLER", "AURORA", "CORONA", "KUIPER", "MATTER"]
  },
  "WEATHER": {
    4: ["RAIN", "WIND", "HAZE", "MIST", "SNOW", "HAIL", "COLD", "WARM", "COOL", "MILD", "GUST", "GALE", "CALM", "DAMP", "THAW", "MELT", "CELL", "FAIR", "HEAT"],
    5: ["STORM", "CLOUD", "FROST", "SLEET", "HUMID", "CRISP", "CHILL", "FRONT", "CLEAR", "BLEAK", "POLAR", "DRAFT", "SURGE", "VAPOR", "BALMY", "DRENCH", "BRISK"],
    6: ["BREEZE", "FREEZE", "WINTER", "SUMMER", "SPRING", "AUTUMN", "SEASON", "SHOWER", "DELUGE", "CIRRUS", "NIMBUS", "SQUALL", "VORTEX", "FRIGID"]
  },
  "KITCHEN": {
    4: ["FORK", "DISH", "BOWL", "OVEN", "COOK", "BAKE", "CHOP", "SALT", "HERB", "MEAL", "WINE", "TRAY"],
    5: ["KNIFE", "PLATE", "SPOON", "STOVE", "FRIDGE", "SPICE", "ROAST", "WHISK", "BAKER", "GRATE", "MIXER", "GLASS", "APRON"],
    6: ["PANTRY", "KETTLE", "SAUCER", "NAPKIN", "FREEZE", "SILVER", "GRATER", "RECIPE", "DINNER"]
  },
  "DESERT": {
    4: ["SAND", "DUNE", "ARID", "HEAT", "DUST", "ROCK", "WIND", "BONE", "BUSH", "GOBI", "MESA",],
    5: ["CACTUS", "CAMEL", "ADOBE", "SNAKE", "OASIS", "SCORP", "DRYLY", "QUARTZ", "BLUFF", "DUNES", "NOMAD", "SHADE"],
    6: ["MIRAGE", "COYOTE", "CANARY", "CANYON", "LIZARD", "BARREN", "SAHARA", "FALCON", "SCORCH", "JACKAL", "GEYSER"]
  },
  "CASTLE": {
    4: ["MOAT", "GATE", "KEEP", "WALL", "KING", "DUKE", "LORD", "FLAG", "GOLD", "IRON", "MAID", "BELL"],
    5: ["TOWER", "COURT", "CROWN", "GUARD", "QUEEN", "ARMOR", "FORGE", "SWORD", "SIEGE", "REIGN", "STAIR", "VAULT"],
    6: ["TURRET", "PALACE", "THRONE", "PRISON", "BRIDGE", "BANNER", "SHIELD", "KNIGHT", "SENTRY", "CHURCH", "ARMORY"]
  },
  "GARDEN": {
    4: ["ROSE", "SEED", "DIRT", "HOSE", "PLOT", "GROW", "YARD", "TOOL", "ROOT", "WEED", "LILY", "IRIS", "FERN"],
    5: ["PLANT", "BLOOM", "PETAL", "GNOME", "MULCH", "PRUNE", "DAISY", "TULIP", "GRASS", "SNAIL", "WATER", "SHEAR"],
    6: ["FLOWER", "SHOVEL", "ORCHID", "VIOLET", "BONSAI", "AZALEA", "ANNUAL", "GARDEN", "BRANCH", "POLLEN", "INSECT"]
  },
  "FOREST": {
    4: ["DEER", "FERN", "MOSS", "PINE", "TREE", "LEAF", "BARK", "TWIG", "ROOT", "BUSH", "WOOD", "BEAR", "WOLF", "VINE", "SOIL", "BIRD", "LIMB", "NEST", "SEED"],
    5: ["CABIN", "TRAIL", "RIVER", "BIRCH", "BRUSH", "TRUNK", "ACORN", "FUNGI", "FLORA", "FAUNA", "SHADE", "CREEK", "HUMUS", "BERRY", "SHRUB", "STUMP"],
    6: ["VALLEY", "CANOPY", "STREAM", "TIMBER", "BRANCH", "BEETLE", "SPIDER", "FUNGUS", "LICHEN", "INSECT", "POLLEN", "RABBIT", "SPRUCE", "NATURE", "RANGER"]
  },
  "CITY": {
    4: ["TAXI", "ROAD", "PARK", "STOP", "SIGN", "SHOP", "CURB", "CAFE", "GRID", "LOFT", "WORK", "SMOG", "LANE", "FLAT", "MART", "NEON"],
    5: ["TRAIN", "METRO", "PLAZA", "BLOCK", "TOWER", "BRICK", "LIGHT", "STORE", "HOTEL", "BENCH", "CROWD", "ALLEY"],
    6: ["BRIDGE", "SUBWAY", "AVENUE", "MUSEUM", "MARKET", "SQUARE", "OFFICE", "GARAGE", "TUNNEL", "STREET"]
  },
  "MUSIC": {
    4: ["NOTE", "SONG", "BEAT", "DRUM", "BASS", "ROCK", "JAZZ", "BAND", "SING", "TONE", "LUTE", "TUNE", "RIFF", "SOLO", "TRIO", "FOLK", "HARP", "OBOE", "ARIA", "CODA", "OPUS", "CLEF"],
    5: ["ALBUM", "PIANO", "VOICE", "GENRE", "LYRIC", "CHORD", "PITCH", "TEMPO", "CELLO", "FLUTE", "BANJO", "ORGAN", "SHARP", "STAGE", "SOUND"],
    6: ["GUITAR", "VIOLIN", "SINGER", "RHYTHM", "CHORUS", "MELODY", "BRIDGE", "RECORD", "STUDIO", "ARTIST", "ENCORE", "SONATA", "BALLAD", "RAPPER", "STRING", "CYMBAL", "FIDDLE", "PICKUP"]
  },
  "SPORTS": {
    4: ["BALL", "GOAL", "TEAM", "GAME", "CLUB", "GOLF", "SWIM", "RACE", "FOUL", "PLAY", "PUCK", "PASS", "JUMP", "DUNK", "KICK", "PUNT"],
    5: ["MATCH", "COURT", "SCORE", "COACH", "ARENA", "TRACK", "FIELD", "PITCH", "JUDGE", "POINT", "RUGBY", "MEDAL"],
    6: ["SOCCER", "TENNIS", "PLAYER", "LEAGUE", "JERSEY", "HOCKEY", "BOXING", "SPRINT", "HELMET", "TACKLE", "ASSIST", "UMPIRE", "KARATE"]
  },
  "THEATER": {
    4: ["PLAY", "CAST", "PROP", "SHOW", "ROLE", "PLOT", "EXIT", "LINE", "PART", "STAR", "SEAT", "CREW"],
    5: ["STAGE", "ACTOR", "DRAMA", "SCENE", "LIGHT", "DANCE", "LOBBY", "MUSIC", "OPERA"],
    6: ["COMEDY", "SCRIPT", "DIRECT", "TICKET", "SCREEN", "CHORUS", "DIALOG", "ENCORE"]
  }
};
