const WORD_LIBRARY = {
  "OCEAN": {
    4: ["FISH", "CLAM", "CRAB", "TUNA", "WAVE", "SAND", "SALT", "TIDE", "REEF", "KELP", "SURF", "BOAT", "SHIP", "SAIL", "BASS", "ORCA", "BLUE"],
    5: ["SHARK", "WHALE", "CORAL", "SHELL", "BEACH", "SHORE", "WATER", "SQUID", "ALGAE", "DIVER", "SHOAL", "SKATE", "CONCH", "SCUBA", "POLYP"],
    6: ["TURTLE", "OYSTER", "ISLAND", "SPONGE", "MARLIN", "SAILOR", "LAGOON", "PIRATE", "SHRIMP", "MARINE", "TRENCH", "SEABED", "MUSSEL", "URCHIN"]
  },
  "SPACE": {
    4: ["MOON", "STAR", "MARS", "VOID", "DUST", "NASA", "NOVA", "ATOM", "TAIL", "RING", "HALO", "DARK", "WARP", "WAVE", "GLOW", "TIME", "SHIP", "LIFE"],
    5: ["ORBIT", "SOLAR", "COMET", "VENUS", "EARTH", "ALIEN", "LUNAR", "PLUTO", "TITAN", "LIGHT", "QUARK", "BOSON", "ALIEN", "FIELD", "FLARE", "GAMMA"],
    6: ["PLANET", "GALAXY", "METEOR", "ROCKET", "NEBULA", "SATURN", "URANUS", "APOLLO", "COSMOS", "QUASAR", "PULSAR", "PHOTON", "HUBBLE", "KEPLER", "AURORA", "CORONA", "KUIPER", "MATTER"]
  },
  "WEATHER": {
    4: ["RAIN", "WIND", "HAZE", "MIST", "SNOW", "HAIL", "COLD", "WARM", "COOL", "MILD", "GUST", "GALE", "CALM", "DAMP", "THAW", "MELT", "CELL", "FAIR", "HEAT"],
    5: ["STORM", "CLOUD", "FROST", "SLEET", "HUMID", "CRISP", "CHILL", "FRONT", "CLEAR", "BLEAK", "POLAR", "DRAFT", "SURGE", "VAPOR", "BALMY", "DRENCH", "BRISK"],
    6: ["BREEZE", "FREEZE", "WINTER", "SUMMER", "SPRING", "AUTUMN", "SEASON", "SHOWER", "DELUGE", "CIRRUS", "NIMBUS", "SQUALL", "VORTEX", "FRIGID"]
  },
  "FOREST": {
    4: ["DEER", "FERN", "MOSS", "PINE", "TREE", "LEAF", "BARK", "TWIG", "ROOT", "BUSH", "WOOD", "BEAR", "WOLF", "VINE", "SOIL", "BIRD", "LIMB", "NEST", "SEED"],
    5: ["CABIN", "TRAIL", "RIVER", "BIRCH", "BRUSH", "TRUNK", "ACORN", "FUNGI", "FLORA", "FAUNA", "SHADE", "CREEK", "HUMUS", "BERRY", "SHRUB", "STUMP"],
    6: ["VALLEY", "CANOPY", "STREAM", "TIMBER", "BRANCH", "BEETLE", "SPIDER", "FUNGUS", "LICHEN", "INSECT", "POLLEN", "RABBIT", "SPRUCE", "NATURE", "RANGER"]
  }
};
